In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [2]:
m = nn.Conv2d(16, 33, 3, padding=0)

input = torch.randn(20,16,50,100)
_input = input.numpy()
out = m(input)

In [3]:
pool = nn.MaxPool2d(2, stride=2, return_indices=True)
unpool = nn.MaxUnpool2d(2, stride=2)
input = torch.tensor([[[[ 1.,  2,  3,  4],
                            [ 5,  6,  7,  8],
                            [ 9, 10, 11, 12],
                            [13, 14, 15, 16]]]])
output, indices = pool(input)
a=pool(input)

In [27]:
a = torch.randn((3, 10))
b = torch.randn((3,10))
c = a -b
d= c**2
dT= d.T

In [25]:
#***STUDENT T DISTRIBUTION TEST***
#q_ij = 1/(1+dist(z_i, u_j)^2), then normalize it.
centroids = np.array(
    [[1,1,1,1],
    [3,3,3,3],
    [6,6,6,6]]
) #u, 3 classes, each class centroid is 4D vector
emb1 = np.array([[13,14,15,16],])
emb2 = np.array([[17,18,19,20],])
embs = np.array([emb1, emb2])#z, 2 samples, each sample embedded to 4D vector

z_minus_u = embs - centroids # diff between each z and each centroids
print('centroids(u):')
print(centroids)
print('---')
print('embs(z):')
print(embs)
print('---')
print('z_minus_u:')
print(z_minus_u)
z_minus_u_square = np.square(z_minus_u)  # i.e., distance square between each z and each centroids
dist_square_sum = np.sum(z_minus_u_square, axis=2) # each element: square of euclid distance
print('---')
print('z_minus_u_square:')
print(z_minus_u_square)
print('---')
print('dist_square_sum:')
print(dist_square_sum)
alpha = 1.
qij = 1. / (1. + dist_square_sum / 1.) # each element: the probability of sample i belong to j
print('---')
print('qij:')
print(qij)
qij_sum = np.sum(qij, axis=1) # sum probability to all 3 centroid
print('---')
print('qij_sum:')
print(qij_sum)
qij_t = np.transpose(qij)
print('---')
print('qij_t:')
print(qij_t)
qij_normalize = qij_t / qij_sum # each probability/sum probability
print('---')
print('qij_normalize:')
print(qij_normalize)
print('---')
print('qij_normalize_t:')
print(qij_normalize.T) # transpose back to denote the probability of i belong to j

centroids(u):
[[1 1 1 1]
 [3 3 3 3]
 [6 6 6 6]]
---
embs(z):
[[[13 14 15 16]]

 [[17 18 19 20]]]
---
z_minus_u:
[[[12 13 14 15]
  [10 11 12 13]
  [ 7  8  9 10]]

 [[16 17 18 19]
  [14 15 16 17]
  [11 12 13 14]]]
---
z_minus_u_square:
[[[144 169 196 225]
  [100 121 144 169]
  [ 49  64  81 100]]

 [[256 289 324 361]
  [196 225 256 289]
  [121 144 169 196]]]
---
dist_square_sum:
[[ 734  534  294]
 [1230  966  630]]
---
qij:
[[0.00136054 0.00186916 0.00338983]
 [0.00081235 0.00103413 0.00158479]]
---
qij_sum:
[0.00661953 0.00343126]
---
qij_t:
[[0.00136054 0.00081235]
 [0.00186916 0.00103413]
 [0.00338983 0.00158479]]
---
qij_normalize:
[[0.20553476 0.2367491 ]
 [0.28237018 0.3013838 ]
 [0.51209507 0.4618671 ]]
---
qij_normalize_t:
[[0.20553476 0.28237018 0.51209507]
 [0.2367491  0.3013838  0.4618671 ]]
